modLoader="javafml"
loaderVersion="${forge_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_url}"
[[mods]]
   modId="copycats"
   version="${version}"
   displayName="${mod_name}"
   updateJSONURL="${mod_update_url}"
   displayURL="${mod_homepage_url}"
   logoFile="${mod_icon}"
   credits="${mod_credits}"
   authors="${mod_authors}"
   description='''${mod_description}'''

[[dependencies.copycats]]
   modId="forge"
   mandatory=true
   versionRange="${forge_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.copycats]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_forge_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.copycats]]
   modId="create"
   mandatory=true
   versionRange="${create_forge_range}"
   ordering="NONE"
   side="BOTH"
